### PR TITLE
added obj files and generic.nav for testing

### PR DESCRIPTION
**Pull request by gedads**
added all current .obj to allow people to test/edit/modify/improve navmeshes
.nav are all made with default settings and may require tweaking within recastdemo

### CODE REVIEW

**Comment by bendangelo** [comment]
It doesn't make sense for me to merge this but I will use this to create navmeshes. You said the navs were created using default settings? What do you mean? At a minimum the tilesize should be set to 256.

**Comment by gedads** [comment]
yes, 0.4 cell size and 256 for tilesize (for all maps, no adjustment done).The idea was to have people play with either.nav or objs and report what's not right and also to get back some space for my dropbox (and maybe, but just a bit, to test my new fiber optic connection)

**Comment by bendangelo** [comment]
This looks pretty good. I'm going to take a deeper look at this tonight.

**Comment by bendangelo** [comment]
boneyard gully is wrong I get errors. To test go spawn a pet and run around.

**Comment by bendangelo** [comment]
Qulun dome is wrong as well.

**Comment by bendangelo** [comment]
Cloister of Tides is acting kind of funky. Spawn a pet and run around the entrance, my shiva flew into the air and didn't come back.

**Comment by bendangelo** [comment]
Sacrificial_Chamber is broken as well, getting navmesh errors. I tested from the entrance before entering an event

**Comment by bendangelo** [comment]
All the navmeshes look good, except the battlefield maps--which we talked about. I have added almost everything except Seekers of Adoulin maps and most battlefield maps.

**Comment by bendangelo** [comment]
I'm going to close this. I have added all navmeshes except for these ones:

```
Horlais Peak ("Burning Circle")
Waughroon Shrine ("Burning Circle")
Balga's Dais ("Burning Circle")
Qu'Bia Arena ("Burning Circle")
Chamber of Oracles ("Shimmering Circle")
Sacrificial Chamber ("Mahogany Door")
Throne Room ("Throne Room"?)
Spire of Dem ("Web of Recollections")
Spire of Mea ("Web of Recollections")
Spire of Holla ("Web of Recollections")
Spire of Vahzl ("Web of Recollections")
The Shrouded Maw ("Memento Circle")
Monarch Linn ("Spatial Displacement")
Mine Shaft #2716 ("Shaft Entrance")
Boneyard Gully ("Dark Miasma")
Bearclaw Pinnacle ("Wind Pillar")
Stellar Fulcrum ("Qe'lov Gate")
Monarch Linn ("Spatial Displacement")
Boneyard Gully ("Dark Miasma")
```

These navmeshes have to be redone because of missing pieces. You can easily just copy and paste in the missing parts and renav it. Please open up a new PR with only the needed navmeshes.

Thanks, great work. We will have to do something about the doors soon.

**Pull request closed without merging**
